### ISSUE TITLE
Segmentation fault in version 0.6.2

### ISSUE THREAD

**Issue by hanzyd** [openSUSE/rapidquilt#13] opened 2021-02-19 12:20 UTC
```
$ cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20210217"

$ zypper info rapidquilt
Loading repository data...
Reading installed packages...


Information for package rapidquilt:
-----------------------------------
Repository     : kernel-tools
Name           : rapidquilt
Version        : 0.6.2-7.18
Arch           : x86_64
Vendor         : obs://build.opensuse.org/Kernel
Installed Size : 1.2 MiB
Installed      : Yes
Status         : up-to-date
Source package : rapidquilt-0.6.2-7.18.src

This is in kernel-sources project:

branch: origin/openSUSE-15.2
commit: dd8c912bb4febd347eea4873aa2274d4583b1abc

$ export RUST_BACKTRACE=full
$ scripts/sequence-patch.sh --dir /dev/shm/quilt --rapid
Creating tree in /dev/shm/quilt/linux-5.3-openSUSE-15.2
Cleaning up from previous run
Linking from /dev/shm/quilt/linux-5.3.orig
thread '<unnamed>' panicked at 'attempted to leave type `nodrop::NoDrop<(epoch::Epoch, garbage::Bag)>` uninitialized, which is invalid', /home/abuild/rpmbuild/BUILD/rustc-1.49.0-src/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0:     0x5603d7ef91ff - <unknown>
   1:     0x5603d7ea30ac - <unknown>Applying 17922 patches using 8 threads...

   2:     0x5603d7ef8814 - <unknown>
   3:     0x5603d7ef80f5 - <unknown>
   4:     0x5603d7ef756d - <unknown>
   5:     0x5603d7f13dae - <unknown>
   6:     0x5603d7f13d4c - <unknown>
   7:     0x5603d7f13cfd - <unknown>
   8:     0x5603d7ea1b10 - <unknown>
   9:     0x5603d7ea192c - <unknown>
  10:     0x5603d7ea6ac5 - <unknown>
  11:     0x5603d7f18198 - <unknown>
  12:     0x5603d7ea681f - <unknown>
  13:     0x5603d7eeea73 - <unknown>
  14:     0x5603d7eee08a - <unknown>
  15:     0x5603d7eee318 - <unknown>
  16:     0x5603d7eef1c9 - <unknown>
  17:     0x5603d7ef0ae3 - <unknown>
  18:     0x5603d7f1cb6a - <unknown>
  19:     0x7f5aae01f299 - start_thread
  20:     0x7f5aadf25af3 - __clone
  21:                0x0 - <unknown>
scripts/sequence-patch.sh: line 78:  5888 Segmentation fault      (core dumped) rapidquilt push -a -d $PATCH_DIR -p $PWD $fuzz $DRY_RUN
[ Tree: /dev/shm/quilt/linux-5.3-openSUSE-15.2 ]
```

**Comment by michalsrb** [comment] 2021-02-19 12:43
Segmentation fault must be a caused by some `unsafe` code. Rapidquilt itself contains very few `unsafe`s and I wouldn't suspect any of them. So it is most likely some dependency.

My main suspects would be `rayon` and `jemallocator`. Try updating them to newer version. Some bug in them probably got exposed by compiling with newer rustc.

**Comment by hanzyd** [comment] 2021-02-19 12:55
rapidquilt is coming from openSUSE repositories. I have not build it myself.

**Comment by michalsrb** [comment] 2021-02-19 14:39
That was meant as suggestion for current rapidquilt maintainers, not aimed directly at you, sorry for the confusion.

**Comment by hanzyd** [comment] 2021-02-23 19:46
Just to add. This happens to me for origin/SLE15-SP2, origin/SLE15-SP3, origin/master ...

**Comment by hramrach** [comment] 2021-02-25 21:47
Should be fixed

**Closed by hramrach** 2021-02-25 21:47 UTC

**Comment by hanzyd** [comment] 2021-02-26 08:08
Thanks! I could confirm, it is fixed for me.

$ zypper info rapidquilt
Loading repository data...
Reading installed packages...


Information for package rapidquilt:
-----------------------------------
Repository     : kernel-tools
Name           : rapidquilt
Version        : 0.6.3-2.1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/Kernel
Installed Size : 1.3 MiB
Installed      : Yes
Status         : up-to-date
Source package : rapidquilt-0.6.3-2.1.src
